##################################################
# active profile
##################################################
spring.profiles.active: dev

##################################################
# default settings
##################################################
service:
    users:
        username: user
        password: password
        roles:    ADMIN
    files:
        basePath:   /tmp/cv-service/
        sourcePath: ${service.files.basePath}source/
        targetPath: ${service.files.basePath}target/
        filename:   Rodrigo-Costa

multipart:
    maxFileSize:    128KB
    maxRequestSize: 128KB

---
##################################################
spring.profiles: dev
##################################################
service.files.basePath: ${HOME}/workspace/chuvadasquatro/cv-service/data/

---
##################################################
spring.profiles: prod
##################################################
service.files.basePath: /tmp/cv-service/
